### ISSUE TITLE
IE11 has problems with JS

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#565]
### Steps to reproduce the issue
- Just open the NMM in IE11

### Expected result
- A working NMM

### Actual result
- A broken NMM

### System information (as much as possible)
- Windows 10
- IE 11

### Additional comments
These are the errors possibly shown in the console of IE11 with stack

![image](https://user-images.githubusercontent.com/13379595/41655497-b33ac0a2-74aa-11e8-96a9-7d4512105ed4.png)

- Object doesn't support property or method 'startsWith'

> "TypeError: Object doesn't support property or method 'startsWith'
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:73955)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:73926)
>    at e.default.methods.findDrive (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:73875)
>    at e.default.computed.crumbs (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:73513)
>    at ba.prototype.get (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:5648)
>    at ba.prototype.evaluate (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:6638)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:1:19440)
>    at t.exports.render (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:74113)
>    at t.p"

- 'Promise' is undefined
> "ReferenceError: 'Promise' is undefined
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:114084)
>    at T.prototype.dispatch (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:3396)
>    at dispatch (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:2716)
>    at e.default.mounted (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:56232)
>    at jt (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:1:17430)
>    at wa.insert (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:7449)
>    at S (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:20092)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:21570)
>    at t.prototype._update (http://localhost/media-manager-improvement/media/com_media/js/mediamanager"

- Object doesn't support property or method 'find'
> "TypeError: Object doesn't support property or method 'find'
>    at i (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:14767)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:15480)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:15446)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:6:113857)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:3204)
>    at Anonymous function (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:3182)
>    at T.prototype._withCommit (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:4447)
>    at T.prototype.commit (http://localhost/media-manager-improvement/media/com_media/js/mediamanager.min.js:11:3154)
>    at commit (http://localhost/media"

**Comment by laoneo** [comment]
Is the promise issue because of #561?

**Comment by schnuti** [comment]
A promise is used in 561 because this is what upload is using. In both cases callbacks would do if you do not chain the promises anyway.

**Comment by kasvith** [comment]
I think promise issue is from upstream. files are retrieving with promises

**Comment by schnuti** [comment]
Sorry for not reporting the problem before. I thought it was known. IE 11 never accepted to start the new MM. i.e. it's not a new issue.

![screenshot_1](https://user-images.githubusercontent.com/956537/41701389-9e22014e-752c-11e8-9fa9-b07a09799fd7.jpg)

**Comment by kasvith** [comment]
yes, its not from your code

**Comment by dgrammatiko** [comment]
@kasvith since I don't have a VM with IE11 atm, can you do a simple test for me?
open https://github.com/joomla-projects/media-manager-improvement/blob/dev/media/vendor/webcomponentsjs/js/webcomponents-sd-ce-pf.min.js

remove all contents and paste the contents from https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-bundle.js

check that promises and all the other missing polyfills are loaded.

If so I will make the needed changes

**Comment by kasvith** [comment]
@dgrammatiko tried pasting the above file and i still gets the same issue
